### ISSUE TITLE
Custom 2022-08-1k

### ISSUE THREAD

**Issue by kennysino** [wjz304/test#6]
{"platform":"DS920+","version":"7.1.1-42951","dtb":"https://github.com/wjz304/Redpill_CustomBuild/files/9235961/ds920p_dts.zip","sn":"20C0SBRBAXMNT","mac":"001132E53517","usb":"0x0751, 0x05e3","ext":"e1000e","exp":"pocopico","jun":"0"}

**Comment by wjz304** [comment]
不要再这测试，我怕影响其他人编译 所以拉了一个临时库
