### ISSUE TITLE
Custom XXX

### ISSUE THREAD

**Issue by Auto-7x24** [wjz304/test#7]
{
    "platform":"DS3622xs+",  
    "version":"7.0.1-42218",  
    "sn":"1980PDN002189",
    "ext":"r8125, e1000, e1000e, vmxnet3"  
}

**Comment by wjz304** [comment]
https://user-images.githubusercontent.com/5615843/187618948-86cdcb16-893d-4d6a-a12d-3eab7931d234.mp4

**Comment by wjz304** [comment]
delete artifacts

**Comment by wjz304** [comment]
delete artifacts

**Comment by wjz304** [comment]
delete build

**Comment by wjz304** [comment]
delete build

**Comment by wjz304** [comment]
delete build

**Comment by wjz304** [comment]
delete builds

**Comment by wjz304** [comment]
delete builds

**Comment by wjz304** [comment]
delete builds

**Comment by wjz304** [comment]
delete builds

**Comment by wjz304** [comment]
delete builds

**Comment by wjz304** [comment]
delete builds

**Comment by wjz304** [comment]
delete builds

**Comment by wjz304** [comment]
delete builds

**Comment by wjz304** [comment]
delete builds

**Comment by wjz304** [comment]
delete builds

**Comment by wjz304** [comment]
delete builds

**Comment by wjz304** [comment]
delete builds

**Comment by wjz304** [comment]
delete builds

**Comment by wjz304** [comment]
delete builds
